export enum ROUTE_NAME {
  AUTH = 'AUTH.LOGIN',
  // Main
  HOME = 'MAIN.HOME',
  ABOUT = 'MAIN.ABOUT',
  USER_PROFILE = 'USER.PROFILE',
  USER_ROLE_REQUEST = 'USER.ROLE_REQUEST',
  // Shop
  SHOP_CART = 'SHOP.CART',
  SHOP_CATEGORY = 'SHOP.CATEGORY',
  SHOP_CHECKOUT = 'SHOP.CHECKOUT',
  SHOP_OFFER = 'SHOP.OFFER',
  SHOP_ORDER = 'SHOP.ORDER',
  SHOP_ORDERS = 'SHOP.ORDERS',
  SHOP_SEARCH = 'SHOP.SEARCH',
  SHOP_STORE = 'SHOP.STORE',
  SHOP_STORES = 'SHOP.STORES',
  // VENDOR
  VENDOR_AUTH = 'VENDOR.AUTH',
  VENDOR_HOME = 'VENDOR.HOME',
  VENDOR_OFFER = 'VENDOR.OFFER',
  VENDOR_OFFERS = 'VENDOR.OFFERS',
  VENDOR_ORDER = 'VENDOR.ORDER',
  VENDOR_ORDERS = 'VENDOR.ORDERS',
  VENDOR_STORE = 'VENDOR.STORE',
  VENDOR_STORES = 'VENDOR.STORES',
}
